version: "2"

linters:
  default: none
  enable:
    # 基础检查
    - govet
    - staticcheck
    - errcheck
    - unused

    # 风格
    - revive
    - unconvert

    # 安全
    - gosec

    # 并发
    - bodyclose
    - noctx
  settings:
    gosec:
      excludes:
        - G115

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - mnd
          - lll
          - errcheck
      - path: _test\.go
        linters:
          - gosec
        text: "G104:"
      - path: _test\.go
        linters:
          - revive
        text: "unused-parameter:"

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines