// Copyright 2022 The codesjoy Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"strings"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	contextPackage     = protogen.GoImportPath("context")
	xerrorPackage      = protogen.GoImportPath("github.com/codesjoy/pkg/basic/xerror")
	streamPackage      = protogen.GoImportPath("github.com/codesjoy/yggdrasil/v3/stream")
	clientPackage      = protogen.GoImportPath("github.com/codesjoy/yggdrasil/v3/client")
	interceptorPackage = protogen.GoImportPath("github.com/codesjoy/yggdrasil/v3/interceptor")
	serverPackage      = protogen.GoImportPath("github.com/codesjoy/yggdrasil/v3/server")
	metadataPackage    = protogen.GoImportPath("github.com/codesjoy/yggdrasil/v3/metadata")
	codePackage        = protogen.GoImportPath("google.golang.org/genproto/googleapis/rpc/code")
)

func generateFiles(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Services) == 0 {
		return
	}
	generateRPCFile(gen, file)
}

func generateRPCFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_rpc.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	generateHeader(g, file)
	generateFileContent(gen, file, g)
}

func generateHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("// Code generated by protoc-gen-yggdrasil-rpc. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
}

func generateFileContent(_ *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	g.P("// This is a compile-time assertion to ensure that this generated file")
	g.P("// is compatible with the yggdrasil package it is being compiled against.")
	g.P("var _ = new(", metadataPackage.Ident("MD"), ")")
	g.P()

	for _, service := range file.Services {
		if len(service.Methods) > 0 {
			genService(g, service, file)
		}
	}
}

func genService(g *protogen.GeneratedFile, service *protogen.Service, file *protogen.File) {
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P("//")
		g.P(deprecationComment)
	}

	sd := &serviceDesc{
		Filename:              file.GeneratedFilenamePrefix + ".proto",
		ServiceType:           service.GoName,
		ServiceName:           string(service.Desc.FullName()),
		FullServerName:        string(service.Desc.FullName()),
		LowerFirstServiceType: toLowerFirstCamelCase(service.GoName),
		Context:               g.QualifiedGoIdent(contextPackage.Ident("Context")),
		Code:                  g.QualifiedGoIdent(codePackage.Ident("")),
		Status:                g.QualifiedGoIdent(xerrorPackage.Ident("")),
		Client:                g.QualifiedGoIdent(clientPackage.Ident("")),
		Server:                g.QualifiedGoIdent(serverPackage.Ident("")),
		Md:                    g.QualifiedGoIdent(metadataPackage.Ident("")),
		NeedStream:            false,
		HasUnaryMethods:       false,
	}
	streamIndex := 0
	for _, method := range service.Methods {
		tmp := &methodDesc{
			Name:         method.GoName,
			Input:        g.QualifiedGoIdent(method.Input.GoIdent),
			Output:       g.QualifiedGoIdent(method.Output.GoIdent),
			ClientStream: method.Desc.IsStreamingClient(),
			ServerStream: method.Desc.IsStreamingServer(),
		}
		tmp.IsUnary = !tmp.ClientStream && !tmp.ServerStream
		tmp.IsBidi = tmp.ClientStream && tmp.ServerStream
		tmp.IsClientStreamOnly = tmp.ClientStream && !tmp.ServerStream
		tmp.IsServerStreamOnly = !tmp.ClientStream && tmp.ServerStream
		if tmp.ClientStream || tmp.ServerStream {
			sd.NeedStream = true
			tmp.StreamIndex = streamIndex
			streamIndex++
		}
		if tmp.IsUnary {
			sd.HasUnaryMethods = true
		}
		sd.Methods = append(sd.Methods, tmp)
	}
	if sd.NeedStream {
		sd.Stream = g.QualifiedGoIdent(streamPackage.Ident(""))
	}
	if sd.HasUnaryMethods {
		sd.Interceptor = g.QualifiedGoIdent(interceptorPackage.Ident(""))
	}
	if len(sd.Methods) != 0 {
		g.P(sd.execute(tpl))
	}
}

// toLowerFirstCamelCase returns the given string in camelcase formatted string
// but with the first letter being lowercase.
func toLowerFirstCamelCase(s string) string {
	if s == "" {
		return s
	}
	if len(s) == 1 {
		return strings.ToLower(string(s[0]))
	}
	s = strToCamelCase(s)
	return strings.ToLower(string(s[0])) + s[1:]
}

// strToCamelCase converts from underscore separated form to camel case form.
func strToCamelCase(s string) string {
	if s == "" {
		return ""
	}
	words := strings.ReplaceAll(s, "_", " ")
	caser := cases.Title(language.Und)
	titleStr := caser.String(words)
	return strings.ReplaceAll(titleStr, " ", "")
}

const deprecationComment = "// Deprecated: Do not use."
