yggdrasil:
  app:
    name: "github.com.codesjoy.yggdrasil.example.13-error-reason.client"
  admin:
    application:
      namespace: "dev"
  clients:
    defaults:
      interceptors:
        unary:
          - "logging"
        stream:
          - "logging"
    services:
      github.com.codesjoy.yggdrasil.example.13-error-reason:
        remote:
          endpoints:
            - address: "127.0.0.1:55884"
              protocol: "grpc"
  observability:
    logging:
      remote_level: debug
      interceptors:
        logging:
          print_req_and_res: true
