yggdrasil:
  app:
    name: "github.com.codesjoy.yggdrasil.example.11-rpc-streaming"
  server:
    transports:
      - "grpc"
    interceptors:
      unary:
        - "logging"
      stream:
        - "logging"

  transports:
    grpc:
      server:
        address: "127.0.0.1:55880"

  observability:
    logging:
      interceptors:
        logging:
          print_req_and_res: true
      handlers:
        default:
          type: "text"
          config:
            level: "debug"
      writers:
        default:
          type: "console"
