yggdrasil:
  server:
    transports:
      - "grpc"
    interceptors:
      unary:
        - "logging"
      stream:
        - "logging"

  transports:
    grpc:
      server:
        address: "127.0.0.1:55879"
    http:
      rest:
        port: 3000
        middleware:
          all:
            - "logger"

  logging:
    remote_level: debug
    interceptors:
      logging:
        PrintReqAndRes: true

    handlers:
      default:
        type: "text"
        config:
          level: "debug"
    writers:
      default:
        type: "console"
