// Copyright 2022 The codesjoy Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"net/http"
	"regexp"
	"strings"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

// Import path constants used to qualify identifiers in generated code.
const (
	httpPkg        = protogen.GoImportPath("net/http")
	ctxPkg         = protogen.GoImportPath("context")
	ioPkg          = protogen.GoImportPath("io")
	marshalerPkg   = protogen.GoImportPath("github.com/codesjoy/yggdrasil/v2/remote/marshaler")
	statusPkg      = protogen.GoImportPath("github.com/codesjoy/pkg/basic/xerror")
	interceptorPkg = protogen.GoImportPath("github.com/codesjoy/yggdrasil/v2/interceptor")
	restPkg        = protogen.GoImportPath("github.com/codesjoy/yggdrasil/v2/remote/rest")
	svrPkg         = protogen.GoImportPath("github.com/codesjoy/yggdrasil/v2/server")
	codePkg        = protogen.GoImportPath("google.golang.org/genproto/googleapis/rpc/code")
)

// methodSets tracks the per-method-name counter used to disambiguate overloaded
// handlers when the same RPC is bound to multiple HTTP routes.
var methodSets = make(map[string]int)

// generateFiles generates a _rest.pb.go file containing yggdrasil errors definitions.
func generateFiles(gen *protogen.Plugin, file *protogen.File) error {
	pass := false
	for _, service := range file.Services {
		for _, method := range service.Methods {
			if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
				continue
			}
			rule, ok := proto.GetExtension(method.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
			if rule != nil && ok {
				pass = true
				break
			}
		}
		if pass {
			break
		}
	}
	if !pass {
		return nil
	}
	filename := file.GeneratedFilenamePrefix + "_rest.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-yggdrasil-rest. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	return generateFileContent(gen, file, g)
}

// generateFileContent generates the yggdrasil errors definitions, excluding the package statement.
func generateFileContent(
	gen *protogen.Plugin,
	file *protogen.File,
	g *protogen.GeneratedFile,
) error {
	g.P("// This is a compile-time assertion to ensure that this generated file")
	g.P("// is compatible with the yggdrasil package it is being compiled against.")
	g.P("var _ = new(", marshalerPkg.Ident("ProtoMarshaller"), ")")
	g.P("var _ = ", ioPkg.Ident("EOF"))

	g.P()
	for _, service := range file.Services {
		if err := genService(gen, file, g, service); err != nil {
			return err
		}
	}
	return nil
}

// genService builds the REST handler functions and service descriptor for a
// single protobuf service. It iterates over all methods, resolves their HTTP
// annotations, and emits the generated Go source via the template engine.
func genService(
	_ *protogen.Plugin,
	_ *protogen.File,
	g *protogen.GeneratedFile,
	service *protogen.Service,
) error {
	if len(service.Methods) == 0 {
		return nil
	}
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P("//")
		g.P(deprecationComment)
	}

	// Build the service descriptor with qualified import paths for generated code.
	sd := &serviceDesc{
		// ChiPkg:         g.QualifiedGoIdent(chiPkg.Ident("")),
		HTTPPkg:        g.QualifiedGoIdent(httpPkg.Ident("")),
		MarshalerPkg:   g.QualifiedGoIdent(marshalerPkg.Ident("")),
		StatusPkg:      g.QualifiedGoIdent(statusPkg.Ident("")),
		RestPkg:        g.QualifiedGoIdent(restPkg.Ident("")),
		SvrPkg:         g.QualifiedGoIdent(svrPkg.Ident("")),
		CodePkg:        g.QualifiedGoIdent(codePkg.Ident("")),
		CtxPkg:         g.QualifiedGoIdent(ctxPkg.Ident("")),
		IoPkg:          g.QualifiedGoIdent(ioPkg.Ident("")),
		InterceptorPkg: g.QualifiedGoIdent(interceptorPkg.Ident("")),

		ServiceType: service.GoName,
		ServiceName: string(service.Desc.FullName()),
	}

	for _, method := range service.Methods {
		if err := buildMethod(sd, g, method); err != nil {
			return err
		}
	}

	// Lazily set ChiPkg only when at least one method has path bindings,
	// so that the chi import is omitted from generated files that don't need it.
	for _, item := range sd.Methods {
		if len(item.PathBindings) > 0 {
			sd.ChiPkg = g.QualifiedGoIdent(
				protogen.GoImportPath("github.com/go-chi/chi/v5").Ident(""),
			)
			break
		}
	}
	g.P(sd.execute())
	return nil
}

// buildMethod processes a single protobuf method. It extracts the HttpRule
// annotation, resolves the main rule and any additional_bindings into
// methodDesc entries, and appends them to the service descriptor.
func buildMethod(sd *serviceDesc, g *protogen.GeneratedFile, method *protogen.Method) error {
	if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
		return nil
	}
	rule, ok := proto.GetExtension(method.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
	if !ok || rule == nil {
		return nil
	}
	for _, bind := range rule.AdditionalBindings {
		item, err := buildHTTPRule(g, method, bind)
		if err != nil {
			return err
		}
		if item == nil {
			continue
		}
		sd.Methods = append(sd.Methods, item)
	}
	item, err := buildHTTPRule(g, method, rule)
	if err != nil {
		return err
	}
	if item == nil {
		return nil
	}
	sd.Methods = append(sd.Methods, item)
	return nil
}

// buildHTTPRule constructs a methodDesc from a single HttpRule. It resolves the
// HTTP method and path, parses path bindings, and determines body/query-param
// handling based on the rule's body field.
//
// Body semantics:
//   - body="*"  → entire request is JSON-decoded; no query params emitted.
//   - body="x"  → field "x" is JSON-decoded; remaining fields populated from query.
//   - body=""   → no body (GET/DELETE); all fields populated from query.
func buildHTTPRule(
	g *protogen.GeneratedFile,
	m *protogen.Method,
	rule *annotations.HttpRule,
) (*methodDesc, error) {
	var (
		path   string
		method string
		body   string
	)
	switch pattern := rule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		path = pattern.Get
		method = "GET"
	case *annotations.HttpRule_Put:
		path = pattern.Put
		method = "PUT"
	case *annotations.HttpRule_Post:
		path = pattern.Post
		method = "POST"
	case *annotations.HttpRule_Delete:
		path = pattern.Delete
		method = "DELETE"
	case *annotations.HttpRule_Patch:
		path = pattern.Patch
		method = "PATCH"
	case *annotations.HttpRule_Custom:
		path = pattern.Custom.Path
		method = pattern.Custom.Kind
	}

	md, err := buildMethodDesc(g, m, method, path)
	if err != nil {
		return nil, err
	}

	body = rule.Body
	if method == http.MethodGet || method == http.MethodDelete {
		if body != "" {
			return nil, fmt.Errorf("%s %s body should not be declared", method, path)
		}
	} else {
		if body == "" {
			return nil, fmt.Errorf("%s %s does not declare a body", method, path)
		}
	}

	switch body {
	case "*":
		md.HasBody = true
		md.HasQueryParams = false
	case "":
		md.HasQueryParams = true
	default:
		md.HasBody = true
		md.HasQueryParams = true
		md.Body = "." + camelCaseVars(body)
		// Store the body field type for initialization in generated code
		if bodyType := getBodyFieldType(g, m.Input, body); bodyType != "" {
			md.BodyType = bodyType
		}
	}

	return md, nil
}

// getBodyFieldType returns the Go type name of the body field from the input message
func getBodyFieldType(g *protogen.GeneratedFile, msg *protogen.Message, bodyField string) string {
	// The bodyField from annotations is typically in snake_case (e.g., "book")
	// We need to match it against the protobuf field name
	for _, field := range msg.Fields {
		// Check if this is the field we're looking for by comparing field names
		// The Desc.Name() returns the protobuf field name in snake_case
		if string(field.Desc.Name()) == bodyField || field.Desc.JSONName() == bodyField {
			// If it's a message type, return the Go type name
			if field.Message != nil {
				return g.QualifiedGoIdent(field.Message.GoIdent)
			}
		}
	}
	return ""
}

// buildMethodDesc creates a partially-populated methodDesc with the method
// name, overload counter, request type, and resolved path bindings.
func buildMethodDesc(
	g *protogen.GeneratedFile,
	m *protogen.Method,
	method, path string,
) (*methodDesc, error) {
	// Increment the overload counter after this function returns so that
	// the next call with the same GoName gets a higher Num value.
	defer func() { methodSets[m.GoName]++ }()
	desc := &methodDesc{
		Name:    m.GoName,
		Num:     methodSets[m.GoName],
		Request: g.QualifiedGoIdent(m.Input.GoIdent),
		Method:  method,
	}
	var err error
	desc.Path, desc.PathBindings, err = buildPathVars(path)
	if err != nil {
		return nil, err
	}
	return desc, nil
}

var (
	// pathPattern extracts brace-delimited path variables from a route template.
	// Captures: group 1 = field path (e.g. "name" or "resource.name"),
	// group 2 = optional template (e.g. "users/*").
	pathPattern = regexp.MustCompile(`{([^{}=]*)(?:=([^{}]*))?}`)

	// fieldPathPattern validates that a binding name is a dotted sequence of
	// lowercase identifiers (e.g. "name", "resource.name").
	fieldPathPattern = regexp.MustCompile(`^[a-z_][a-z0-9_]*(?:\.[a-z_][a-z0-9_]*)*$`)
)

// pathBindingSegment represents one segment of a resolved path binding.
// Exactly one of Literal or Param is set:
//   - Literal: a static path component (e.g. "users", "settings").
//   - Param: a runtime route parameter (e.g. "params1").
type pathBindingSegment struct {
	Literal string
	Param   string
}

// pathVarBinding associates a protobuf field path with its resolved path
// segments. For example, binding "name" in "/v1/{name=organizations/*/settings}"
// produces FieldPath="name" with segments [literal("organizations"), param("params1"), literal("settings")].
type pathVarBinding struct {
	FieldPath string
	Segments  []pathBindingSegment
}

// pathBindingExpansion is an intermediate result from expandPathBinding containing
// the rewritten route string and the structured segments for value reconstruction.
type pathBindingExpansion struct {
	route    string
	segments []pathBindingSegment
}

// buildPathVars parses all brace-delimited bindings in a route path and returns:
//   - route: the rewritten path with placeholders (e.g. "/v1/organizations/{params1}/settings").
//   - bindings: structured field-path-to-segments mappings for each binding.
//   - error: validation failures (empty segments, unsupported wildcards, etc.).
func buildPathVars(path string) (string, []pathVarBinding, error) {
	var bindings []pathVarBinding
	paramsIdx := 0
	matches := pathPattern.FindAllStringSubmatchIndex(path, -1)
	if len(matches) == 0 {
		return path, bindings, nil
	}

	// Rebuild the path string, replacing each {binding} with its expanded route.
	var b strings.Builder
	last := 0
	for _, match := range matches {
		// Copy the literal text between the previous match and this one.
		b.WriteString(path[last:match[0]])

		placeholder := path[match[0]:match[1]]
		name := path[match[2]:match[3]]

		// The template (the part after '=') is optional.
		template := ""
		hasTemplate := match[4] >= 0 && match[5] >= 0
		if hasTemplate {
			template = path[match[4]:match[5]]
		}

		expansion, nextIdx, err := expandPathBinding(
			placeholder,
			name,
			template,
			hasTemplate,
			paramsIdx,
		)
		if err != nil {
			return "", nil, fmt.Errorf("path %q: %w", path, err)
		}
		b.WriteString(expansion.route)
		bindings = append(bindings, pathVarBinding{
			FieldPath: name,
			Segments:  expansion.segments,
		})
		paramsIdx = nextIdx
		last = match[1]
	}
	// Append any trailing literal text after the last binding.
	b.WriteString(path[last:])

	return b.String(), bindings, nil
}

// expandPathBinding resolves a single brace-delimited binding (e.g.
// "{name=organizations/*/settings}") into a rewritten route fragment and a
// list of structured segments. It returns the expansion, the next available
// parameter index, and any validation error.
//
// The sawWildcard flag ensures that the first '*' in a template bumps the
// parameter index by one, reserving paramsIdx for the binding counter and
// using paramsIdx+1 for the first actual wildcard capture. Subsequent '*'
// segments continue incrementing from there.
func expandPathBinding(
	placeholder, name, template string,
	hasTemplate bool,
	paramsIdx int,
) (pathBindingExpansion, int, error) {
	// Step 1: Validate the field path (e.g. "name", "resource.name").
	if !isValidBindingFieldPath(name) {
		return pathBindingExpansion{}, paramsIdx, fmt.Errorf("invalid binding %q", placeholder)
	}

	// Step 2: If there is no template or the template is a single wildcard,
	// the entire binding maps to one placeholder parameter.
	if !hasTemplate || template == "*" {
		param := fmt.Sprintf("{params%d}", paramsIdx)
		return pathBindingExpansion{
			route: param,
			segments: []pathBindingSegment{
				{Param: strings.Trim(param, "{}")},
			},
		}, paramsIdx + 1, nil
	}
	if template == "" {
		return pathBindingExpansion{}, paramsIdx, fmt.Errorf(
			"binding %q has an empty template",
			placeholder,
		)
	}

	// Step 3: Split the template on '/' and classify each segment as either
	// a literal or a wildcard parameter placeholder.
	segments := strings.Split(template, "/")
	routeParts := make([]string, 0, len(segments))
	valueParts := make([]pathBindingSegment, 0, len(segments))
	nextIdx := paramsIdx
	sawWildcard := false
	for _, segment := range segments {
		// Reject empty segments caused by leading/trailing/double slashes.
		if segment == "" {
			return pathBindingExpansion{}, paramsIdx, fmt.Errorf(
				"binding %q contains an empty path segment",
				placeholder,
			)
		}
		// Multi-segment wildcard is not supported by chi router.
		if segment == "**" || strings.Contains(segment, "**") {
			return pathBindingExpansion{}, paramsIdx, fmt.Errorf(
				"binding %q uses unsupported multi-segment wildcard \"**\"",
				placeholder,
			)
		}
		if segment == "*" {
			// The first wildcard in this template increments nextIdx past
			// paramsIdx so that the binding counter slot is skipped.
			if !sawWildcard {
				nextIdx++
				sawWildcard = true
			}
			param := fmt.Sprintf("{params%d}", nextIdx)
			routeParts = append(routeParts, param)
			valueParts = append(valueParts, pathBindingSegment{Param: strings.Trim(param, "{}")})
			nextIdx++
			continue
		}
		// Partial wildcards like "a*b" are not valid.
		if strings.Contains(segment, "*") {
			return pathBindingExpansion{}, paramsIdx, fmt.Errorf(
				"binding %q contains an unsupported wildcard segment %q",
				placeholder,
				segment,
			)
		}
		// Static literal segment.
		routeParts = append(routeParts, segment)
		valueParts = append(valueParts, pathBindingSegment{Literal: segment})
	}
	return pathBindingExpansion{
		route:    strings.Join(routeParts, "/"),
		segments: valueParts,
	}, nextIdx, nil
}

// isValidBindingFieldPath returns true if name is a valid dotted field path
// (e.g. "name", "resource.name") matching the protobuf field naming convention.
func isValidBindingFieldPath(name string) bool {
	return fieldPathPattern.MatchString(name)
}

// camelCaseVars converts a dot-separated snake_case path (e.g. "resource.name")
// into a dot-separated CamelCase path (e.g. "Resource.Name") for use as a Go
// struct field accessor in generated code.
func camelCaseVars(s string) string {
	if s == "" {
		return ""
	}
	var (
		vars []string
		subs = strings.Split(s, ".")
	)
	for _, sub := range subs {
		vars = append(vars, strToCamelCase(sub))
	}
	return strings.Join(vars, ".")
}

// strToCamelCase converts a snake_case identifier to CamelCase (e.g. "user_id" → "UserId").
func strToCamelCase(s string) string {
	if s == "" {
		return ""
	}
	words := strings.ReplaceAll(s, "_", " ")
	caser := cases.Title(language.Und)
	titleStr := caser.String(words)
	return strings.ReplaceAll(titleStr, " ", "")
}

const deprecationComment = "// Deprecated: Do not use."
