yggdrasil:
  admin:
    application:
      namespace: "dev"
  clients:
    defaults:
      interceptors:
        unary:
          - "logging"
        stream:
          - "logging"
    services:
      github.com.codesjoy.yggdrasil.example.11-rpc-streaming:
        remote:
          endpoints:
            - address: "127.0.0.1:55880"
              protocol: "grpc"
  observability:
    logging:
      remote_level: debug
      interceptors:
        logging:
          print_req_and_res: true
