yggdrasil:
  server:
    transports:
      - "grpc"
    interceptors:
      unary:
        - "logging"
      stream:
        - "logging"

  transports:
    grpc:
      server:
        address: "127.0.0.1:55884"

  observability:
    logging:
      interceptors:
        logging:
          print_req_and_res: true
      handlers:
        default:
          type: "text"
          config:
            level: "debug"
      writers:
        default:
          type: "console"
