yggdrasil:
  application:
    namespace: "dev"
  client:
    github.com.codesjoy.yggdrasil.example.advanced.rest:
      remote:
        endpoints:
          - address: "127.0.0.1:55888"
            protocol: "grpc"
  interceptor:
    unary_client: "logging"
    stream_client: "logging"
    config:
      logging:
        print_req_and_res: true

  remote:
    logger_level: debug
