yggdrasil:
  server:
    protocol:
      - "grpc"

  remote:
    protocol:
      grpc:
        address: "127.0.0.1:55884"

  interceptor:
    unary_server: "logging"
    stream_server: "logging"
    config:
      logging:
        print_req_and_res: true

  logger:
    handler:
      default:
        type: "text"
        config:
          level: "debug"
    writer:
      default:
        type: "console"
