yggdrasil:
  mode: dev

  server:
    transports:
      - "grpc"

  transports:
    grpc:
      server:
        address: "127.0.0.1:56023"

  admin:
    governor:
      port: 56024

app:
  custom_cron:
    schedule: "@every 5s"
    job_label: "cron-heartbeat"
